[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.pyright]
timeout = 200
inlay-hints = true


[language-server.ruff]
command = "ruff"
args = ["server"]
