[[language]]
name = "rust"
# language-server = { command = "rust-analyzer", args = ["--stdio"]}
# config = {"rust" = {serverPath = "/home/clebson/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer"}}
[language.config.check]
command = "clippy"

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line